version: '3'

services:
  backend: # RestAPI backend service providing tools for generating prediction and database management
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my_network

  streamlit_app: # User Interfrace frontend web app
    build: ./streamlit_app
    ports:
      - "5005:5005"
    networks:
      - my_network

  db: # MySQL database that stores images with their generated captions
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: train_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
